name: Build & Deploy to SiteGround

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
    # 1 – Check out code
    - uses: actions/checkout@v4

    # 2 – Install Node (no cache flag here)
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3 – Install PNPM *and* restore/save its cache
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        cache: true            # <-- this handles pnpm-store caching for you
        run_install: false

    # 4 – Prove pnpm is on PATH
    - run: pnpm --version

    # 5 – Install deps & build
    - name: Build front-end
      run: |
        pnpm install --filter frontend --no-frozen-lockfile
        pnpm --filter frontend run build            # ➜ frontend/dist/

    # 6 – Copy the static build to SiteGround
    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host:       ${{ secrets.SG_HOST }}
        port:       ${{ secrets.SG_PORT }}
        username:   ${{ secrets.SG_USER }}
        key:        ${{ secrets.SITEGROUND_SSH_KEY }}
        passphrase: ${{ secrets.SG_PASSPHRASE }}     # omit if your key has no passphrase
        source:     "frontend/dist/*"                # everything inside dist/
        target:     "/home/${{ secrets.SG_USER }}/www/taxmybackend.com/public_html/"
        overwrite:  true                             # replace existing files

