name: Build & Deploy to SiteGround

on:
  push:
    branches: [main]              # direct pushes
  pull_request:
    types: [closed]               # runs when a PR is merged

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
    # 1 – Check out repo
    - uses: actions/checkout@v4

    # 2 – Set up Node + pnpm cache
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm                # keyed by pnpm-lock.yaml

    # 3 – Install pnpm and add it to PATH  (this **must** precede any pnpm commands)
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    # 4 – Quick sanity check
    - run: pnpm --version

    # 5 – Install deps & build front-end
    - name: Build front-end
      run: |
        pnpm install --filter frontend --frozen-lockfile
        pnpm --filter frontend run build        # outputs to frontend/dist/

    # 6 – Deploy the static build to SiteGround
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.SG_HOST }}
        port:     ${{ secrets.SG_PORT }}
        username: ${{ secrets.SG_USER }}
        key:      ${{ secrets.SITEGROUND_SSH_KEY }}
        script: |
          rsync -a --delete --quiet \
            ./frontend/dist/ \
            /home/${{ secrets.SG_USER }}/www/taxmybackend.com/public_html/

