name: Build & Deploy to SiteGround

on:
  push:
    branches: [main]            # direct pushes
  pull_request:
    types: [closed]             # fires when a PR is merged

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
    # 1 – Check out the repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2 – Set up Node 20 with pnpm-compatible cache
    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm              # keyed by pnpm-lock.yaml

    # 3 – Install pnpm 8.x and add it to PATH
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false       # we'll install ourselves

    # 4 – Sanity check (shows 8.x.x)
    - run: pnpm --version

    # 5 – Install deps (dev + prod) and build the front-end
    - name: Build front-end
      run: |
        pnpm install --filter frontend --frozen-lockfile
        pnpm --filter frontend run build         # → frontend/dist/

    # 6 – Rsync the static build to SiteGround
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.SG_HOST }}
        port:     ${{ secrets.SG_PORT }}
        username: ${{ secrets.SG_USER }}
        key:      ${{ secrets.SITEGROUND_SSH_KEY }}
        script: |
          rsync -a --delete --quiet \
            ./frontend/dist/ \
            /home/${{ secrets.SG_USER }}/www/taxmybackend.com/public_html/
