name: Build & Deploy to SiteGround

on:
  push:
    branches: [main]            # direct pushes
  pull_request:
    types: [closed]             # merged PRs

jobs:
  deploy:
    # only run when the push is to main OR a PR was merged
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
    # 1 – Check out the repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2 – Set up Node 20 and enable the pnpm cache
    - name: Setup Node 20 + pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm          # uses pnpm-lock.yaml for a deterministic cache key

    # 3 – Install pnpm globally (always ends up on PATH)
    - name: Install pnpm
      run: npm install -g pnpm@8

    # 4 – Install deps & build the front-end
    - name: Build front-end
      run: |
        pnpm install --filter frontend --frozen-lockfile
        pnpm --filter frontend run build     # produces frontend/dist/

    # 5 – Sync the static build to SiteGround
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.SG_HOST }}
        port:     ${{ secrets.SG_PORT }}
        username: ${{ secrets.SG_USER }}
        key:      ${{ secrets.SITEGROUND_SSH_KEY }}
        script: |
          rsync -a --delete --quiet \
            ./frontend/dist/ \
            /home/${{ secrets.SG_USER }}/www/taxmybackend.com/public_html/
