name: Build & Deploy to SiteGround

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
    # 1 – Check out code
    - uses: actions/checkout@v4

    # 2 – Install Node (no cache flag here)
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3 – Install PNPM *and* restore/save its cache
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        cache: true            # <-- this handles pnpm-store caching for you
        run_install: false

    # 4 – Prove pnpm is on PATH
    - run: pnpm --version

    # 5 – Install deps & build
    - name: Build front-end
      run: |
        pnpm install --filter frontend --no-frozen-lockfile
        pnpm --filter frontend run build            # ➜ frontend/dist/

    # 6 – Deploy to SiteGround via rsync/SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.SG_HOST }}
        port:     ${{ secrets.SG_PORT }}
        username: ${{ secrets.SG_USER }}
        key:      ${{ secrets.SITEGROUND_SSH_KEY }}
        script: |
          rsync -a --delete --quiet \
            ./frontend/dist/ \
            /home/${{ secrets.SG_USER }}/www/taxmybackend.com/public_html/
