name: pnpm PATH test
on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Install pnpm 8 and add to PATH ⬇⬇⬇
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # If this step prints 8.x.x the PATH problem is solved
      - run: pnpm --version
