name: Build & Deploy to SiteGround

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      # 1 – check out the repo
      - uses: actions/checkout@v4

      # 2 – Node 20 (no pnpm yet)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3 – pnpm 8 + cache
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          cache: true          # keyed by pnpm-lock.yaml
          run_install: false

      - run: pnpm --version     # sanity check

      # 4 – install deps + build
      - name: Build front-end
        run: |
          pnpm install --filter frontend --frozen-lockfile   # or --no-frozen-lockfile
          pnpm --filter frontend run build                   # → frontend/dist/

      # 5 – rsync the build to SiteGround
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete          # archive, verbose, compress, delete orphans
          path: frontend/dist/              # trailing / ⇒ copy *contents* only
          remote_path: /home/${{ secrets.SG_USER }}/www/taxmybackend.com/public_html/
          remote_host: ${{ secrets.SG_HOST }}
          remote_port: ${{ secrets.SG_PORT }}
          remote_user: ${{ secrets.SG_USER }}
          remote_key: ${{ secrets.SITEGROUND_SSH_KEY }}
          remote_key_pass: ${{ secrets.SG_PASSPHRASE }}     # omit if key has no passphrase
